### ISSUE TITLE
Inference /command not found

### ISSUE THREAD

**Issue by inuuya** [ardha27/AI-Song-Cover-SOVITS#1]
Halo kak! I've been trying to use your tool to train my own voice and some artists since your latest video popped up on my tiktok's fyp. Jadi masalahnya muncul itu pas aku udah selesai train suaranya aku, terus mau ke tahap inference tapi awalnya kena disconnecting issue, kan. Nah katamu bisa pakai comman ctrl + /, tapi aku gak ngelakuin itu malah aku ngedisconnect dan hapus runtime. Karena aku pikir aku juga udah train suara aku tadinya dan filenya kesimpan di gdrive aku langsung aja, ke langkah 1, 2, dan 5 dan ini yang muncul kak.

Aku masukin yang model dan confignya folder trainnya dari GDrive tadi kak, kamu bisa liat sendiri di gambar bawah ini, ya.... tapi malah muncul yang kayak digambar, gimana ya kak? Aku bingung sendiri juga jadinya T_T

Atau apa kita tidak bisa kak pakai yang dari GDrive untuk tahap nomor 5? atau harus upload/buat clone di github?

![image](https://user-images.githubusercontent.com/96777876/234625135-9cc07ef4-269f-444f-936f-b30cf6694956.png)

**Comment by inuuya** [comment]
kalo aku pakai command yang di bagian kena runtime error "ctrl + /" hasilnya  bakal kayak gini kak

![image](https://user-images.githubusercontent.com/96777876/234626954-e8b51d83-2e8d-4bdc-be21-474b6c7cb297.png)

**Comment by ardha27** [comment]
Itu karena depedenciesnya blm diinstal, svc itu diinstal di step 4

**Comment by inuuya** [comment]
Nahhhh makasih banyak kakkk!!! udahhh bisaaaaa

![Uploading image.png…]()
