### ISSUE TITLE
5. Inference

### ISSUE THREAD

**Issue by rushkii** [ardha27/AI-Song-Cover-SOVITS#5]
Mas, ini kenapa ya error bagian `display(AUDIO())`?

![image](https://github.com/ardha27/AI-Song-Cover-SOVITS/assets/47179236/e107fe1e-0fba-494e-8b16-f7971454f44c)

Model: https://huggingface.co/spaces/zomehwh/vits-models/blob/main/pretrained_models/alice/alice.pth (Blue Archive: Tendou Arisu)

Error logs:
```sh
[18:58:20] INFO     [18:58:20] Version: 3.14.1                    

---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

[<ipython-input-20-26778c592e41>](https://localhost:8080/#) in <cell line: 12>()
     10 get_ipython().system('svc infer {AUDIO}.wav -m {MODEL} -na -t {PITCH}')
     11 # Try comment this line below if you got Runtime Error
---> 12 display(Audio(f"/content/{AUDIO}.out.wav", autoplay=True, rate=22050))

2 frames

[/usr/local/lib/python3.10/dist-packages/IPython/lib/display.py](https://localhost:8080/#) in _validate_and_normalize_with_numpy(data, normalize)
    157         waveobj = wave.open(fp,mode='wb')
    158         waveobj.setnchannels(nchan)
--> 159         waveobj.setframerate(rate)
    160         waveobj.setsampwidth(2)
    161         waveobj.setcomptype('NONE','NONE')

ValueError: could not convert string to float: '/content//content/separated/htdemucs/audio/vocals.out.wav'
```

**Comment by ardha27** [comment]
itu form confignya mana kok ilang

**Comment by rushkii** [comment]
> itu form confignya mana kok ilang

Sengaja saya hilangkan soalnya pakai repository model yang berbeda, saya ambil dari https://huggingface.co/spaces/zomehwh/vits-models/tree/main/pretrained_models/alice, nah di repository itu ga ada confignya makanya saya hilangkan takutnya hasilnya ga sesuai.

Apakah pakai model yang berbeda tapi pakai config yg sudah disediakan bisa mas?

**Comment by ardha27** [comment]
harusnya cari model yang sesuai tutorku, bukan malah codenya yang dirubah. Dan itu beda model ya, model yang kupake ditutor itu "so-vits" sedangkan model yang kamu download itu "vits". "so-vits" itu Voice Convertion sedangkan "vits" itu TTS (Text to Speech). kalo mau pake codeku harus model yg sovits, yang ada config.jsonnya

**Comment by ardha27** [comment]
btw itu displaynya error karena ga ada yg didisplay (inferencenya gagal)

**Comment by rushkii** [comment]
> harusnya cari model yang sesuai tutorku, bukan malah codenya yang dirubah. Dan itu beda model ya, model yang kupake ditutor itu "so-vits" sedangkan model yang kamu download itu "vits". "so-vits" itu Voice Convertion sedangkan "vits" itu TTS (Text to Speech). kalo mau pake codeku harus model yg sovits, yang ada config.jsonnya

Ohh baru tau saya beda.

Sekarang saya mencoba kembali menggunakan repository yang versi `sovits-models` tetap error yang sama mas, kira kira salah di mana ya padahal sudah mengikuti tutorialnya?.
Repo: https://huggingface.co/spaces/zomehwh/sovits-models
Model: https://huggingface.co/spaces/zomehwh/sovits-models/blob/main/models/alice/alice.pth
Config: https://huggingface.co/spaces/zomehwh/sovits-models/blob/main/models/alice/config.json
My notebook: https://colab.research.google.com/drive/1IPrayG2xJZuUP6yp9n8s0bFOOmJyZsnH?usp=sharing

![image](https://github.com/ardha27/AI-Song-Cover-SOVITS/assets/47179236/e2405ada-fa39-49f5-89c6-ebc9f9d31d76)

**Comment by ardha27** [comment]
Itu download pake wget kah? Coba arahin cursormu ke file pth di direktori kiri. Brp size filenya

**Comment by rushkii** [comment]
> Itu download pake wget kah? Coba arahin cursormu ke file pth di direktori kiri. Brp size filenya

file path direktori yang mana mas? soalnya banyak

**Comment by ardha27** [comment]
File pth dlm so vits test

**Comment by rushkii** [comment]
> File pth dlm so vits test

Ga ada tombol properties buat lihat file sizenya, ini lgsg dari web huggingface, untuk `config.json`nya `1.67 kB`

![image](https://github.com/ardha27/AI-Song-Cover-SOVITS/assets/47179236/59ccf436-3a6f-4a28-b4de-65e545f19090)

**Comment by rushkii** [comment]
Sepertinya sudah solved mas, kayaknya ini saya salah link di wget buat download config sama modelnya, sebelumnya pakai link front-end, sekarang udah solved setelah saya ganti jadi link download dari model dan confignya, makasih banyak mas 🙏

**Comment by ardha27** [comment]
Arahin aja kursormu ke file pthnya, nanti keliatan propertiesnya

**Comment by ardha27** [comment]
Sudah kuduga
